# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'C14200152_UAS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for C14200152_UAS
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
